import { editions, bookTypes, getRandomCharacter } from "../util";

export type ClassicTitle = {
    title: string;
    author: string;
};

export const classicTitles: ClassicTitle[] = [
    { title: "Romeo and Juliet", author: "William Shakespeare" },
    { title: "Hamlet", author: "William Shakespeare" },
    { title: "Macbeth", author: "William Shakespeare" },
    { title: "Othello", author: "William Shakespeare" },
    { title: "King Lear", author: "William Shakespeare" },
    { title: "A Midsummer Night's Dream", author: "William Shakespeare" },
    { title: "The Tempest", author: "William Shakespeare" },
    { title: "Julius Caesar", author: "William Shakespeare" },
    { title: "Much Ado About Nothing", author: "William Shakespeare" },
    { title: "As You Like It", author: "William Shakespeare" },

    { title: "To Kill a Mockingbird", author: "Harper Lee" },
    { title: "The Great Gatsby", author: "F. Scott Fitzgerald" },
    { title: "Of Mice and Men", author: "John Steinbeck" },
    { title: "The Grapes of Wrath", author: "John Steinbeck" },
    { title: "The Catcher in the Rye", author: "J.D. Salinger" },
    { title: "Moby Dick", author: "Herman Melville" },
    { title: "The Adventures of Huckleberry Finn", author: "Mark Twain" },
    { title: "The Adventures of Tom Sawyer", author: "Mark Twain" },
    { title: "The Scarlet Letter", author: "Nathaniel Hawthorne" },
    { title: "Uncle Tom's Cabin", author: "Harriet Beecher Stowe" },
    { title: "The Call of the Wild", author: "Jack London" },
    { title: "White Fang", author: "Jack London" },
    { title: "The Red Badge of Courage", author: "Stephen Crane" },
    { title: "Sister Carrie", author: "Theodore Dreiser" },
    { title: "An American Tragedy", author: "Theodore Dreiser" },
    { title: "Main Street", author: "Sinclair Lewis" },
    { title: "Babbitt", author: "Sinclair Lewis" },
    { title: "The Sun Also Rises", author: "Ernest Hemingway" },
    { title: "A Farewell to Arms", author: "Ernest Hemingway" },
    { title: "For Whom the Bell Tolls", author: "Ernest Hemingway" },

    { title: "Pride and Prejudice", author: "Jane Austen" },
    { title: "Sense and Sensibility", author: "Jane Austen" },
    { title: "Emma", author: "Jane Austen" },
    { title: "Mansfield Park", author: "Jane Austen" },
    { title: "Northanger Abbey", author: "Jane Austen" },
    { title: "Persuasion", author: "Jane Austen" },
    { title: "Jane Eyre", author: "Charlotte Brontë" },
    { title: "Wuthering Heights", author: "Emily Brontë" },
    { title: "Great Expectations", author: "Charles Dickens" },
    { title: "A Tale of Two Cities", author: "Charles Dickens" },
    { title: "Oliver Twist", author: "Charles Dickens" },
    { title: "David Copperfield", author: "Charles Dickens" },
    { title: "A Christmas Carol", author: "Charles Dickens" },
    { title: "Hard Times", author: "Charles Dickens" },
    { title: "Bleak House", author: "Charles Dickens" },
    { title: "The Pickwick Papers", author: "Charles Dickens" },
    { title: "Middlemarch", author: "George Eliot" },
    { title: "Silas Marner", author: "George Eliot" },
    { title: "Adam Bede", author: "George Eliot" },
    { title: "The Mill on the Floss", author: "George Eliot" },
    { title: "Frankenstein", author: "Mary Shelley" },
    { title: "Dracula", author: "Bram Stoker" },
    { title: "The Strange Case of Dr. Jekyll and Mr. Hyde", author: "Robert Louis Stevenson" },
    { title: "Treasure Island", author: "Robert Louis Stevenson" },
    { title: "Robinson Crusoe", author: "Daniel Defoe" },
    { title: "Gulliver's Travels", author: "Jonathan Swift" },
    { title: "The Canterbury Tales", author: "Geoffrey Chaucer" },
    { title: "Paradise Lost", author: "John Milton" },
    { title: "The Pilgrim's Progress", author: "John Bunyan" },

    { title: "Tess of the d'Urbervilles", author: "Thomas Hardy" },
    { title: "The Mayor of Casterbridge", author: "Thomas Hardy" },
    { title: "Far from the Madding Crowd", author: "Thomas Hardy" },
    { title: "Jude the Obscure", author: "Thomas Hardy" },
    { title: "The Return of the Native", author: "Thomas Hardy" },
    { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
    { title: "The Importance of Being Earnest", author: "Oscar Wilde" },
    { title: "Heart of Darkness", author: "Joseph Conrad" },
    { title: "Lord Jim", author: "Joseph Conrad" },
    { title: "Nostromo", author: "Joseph Conrad" },
    { title: "The Secret Agent", author: "Joseph Conrad" },
    { title: "The Time Machine", author: "H.G. Wells" },
    { title: "The War of the Worlds", author: "H.G. Wells" },
    { title: "The Invisible Man", author: "H.G. Wells" },
    { title: "The Island of Dr. Moreau", author: "H.G. Wells" },

    { title: "War and Peace", author: "Leo Tolstoy" },
    { title: "Anna Karenina", author: "Leo Tolstoy" },
    { title: "The Death of Ivan Ilyich", author: "Leo Tolstoy" },
    { title: "Crime and Punishment", author: "Fyodor Dostoevsky" },
    { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky" },
    { title: "Notes from Underground", author: "Fyodor Dostoevsky" },
    { title: "The Idiot", author: "Fyodor Dostoevsky" },
    { title: "Demons", author: "Fyodor Dostoevsky" },
    { title: "Dead Souls", author: "Nikolai Gogol" },
    { title: "The Overcoat", author: "Nikolai Gogol" },
    { title: "The Government Inspector", author: "Nikolai Gogol" },
    { title: "Fathers and Sons", author: "Ivan Turgenev" },
    { title: "A Sportsman's Sketches", author: "Ivan Turgenev" },
    { title: "The Cherry Orchard", author: "Anton Chekhov" },
    { title: "The Seagull", author: "Anton Chekhov" },
    { title: "Three Sisters", author: "Anton Chekhov" },
    { title: "Uncle Vanya", author: "Anton Chekhov" },

    { title: "Les Misérables", author: "Victor Hugo" },
    { title: "The Hunchback of Notre-Dame", author: "Victor Hugo" },
    { title: "Madame Bovary", author: "Gustave Flaubert" },
    { title: "Sentimental Education", author: "Gustave Flaubert" },
    { title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
    { title: "The Three Musketeers", author: "Alexandre Dumas" },
    { title: "Twenty Years After", author: "Alexandre Dumas" },
    { title: "Candide", author: "Voltaire" },
    { title: "The Red and the Black", author: "Stendhal" },
    { title: "The Charterhouse of Parma", author: "Stendhal" },
    { title: "Père Goriot", author: "Honoré de Balzac" },
    { title: "Eugénie Grandet", author: "Honoré de Balzac" },
    { title: "Lost Illusions", author: "Honoré de Balzac" },
    { title: "Germinal", author: "Émile Zola" },
    { title: "Nana", author: "Émile Zola" },
    { title: "L'Assommoir", author: "Émile Zola" },

    { title: "The Sorrows of Young Werther", author: "Johann Wolfgang von Goethe" },
    { title: "Faust", author: "Johann Wolfgang von Goethe" },
    { title: "Wilhelm Meister's Apprenticeship", author: "Johann Wolfgang von Goethe" },
    { title: "The Magic Mountain", author: "Thomas Mann" },
    { title: "Buddenbrooks", author: "Thomas Mann" },
    { title: "Death in Venice", author: "Thomas Mann" },
    { title: "All Quiet on the Western Front", author: "Erich Maria Remarque" },
    { title: "The Metamorphosis", author: "Franz Kafka" },
    { title: "The Trial", author: "Franz Kafka" },
    { title: "The Castle", author: "Franz Kafka" },
    { title: "America", author: "Franz Kafka" },

    { title: "Don Quixote", author: "Miguel de Cervantes" },
    { title: "La Celestina", author: "Fernando de Rojas" },
    { title: "Life is a Dream", author: "Pedro Calderón de la Barca" },
    { title: "The House of Bernarda Alba", author: "Federico García Lorca" },
    { title: "Blood Wedding", author: "Federico García Lorca" },
    { title: "Yerma", author: "Federico García Lorca" },

    { title: "The Divine Comedy", author: "Dante Alighieri" },
    { title: "The Decameron", author: "Giovanni Boccaccio" },
    { title: "The Prince", author: "Niccolò Machiavelli" },
    { title: "The Betrothed", author: "Alessandro Manzoni" },

    { title: "The Iliad", author: "Homer" },
    { title: "The Odyssey", author: "Homer" },
    { title: "The Aeneid", author: "Virgil" },
    { title: "Oedipus Rex", author: "Sophocles" },
    { title: "Antigone", author: "Sophocles" },
    { title: "Medea", author: "Euripides" },
    { title: "The Oresteia", author: "Aeschylus" },
    { title: "Metamorphoses", author: "Ovid" },
    { title: "The Confessions", author: "Augustine of Hippo" },

    { title: "1984", author: "George Orwell" },
    { title: "Animal Farm", author: "George Orwell" },
    { title: "Brave New World", author: "Aldous Huxley" },
    { title: "Lord of the Flies", author: "William Golding" },
    { title: "The Lord of the Rings", author: "J.R.R. Tolkien" },
    { title: "The Hobbit", author: "J.R.R. Tolkien" },
    { title: "One Flew Over the Cuckoo's Nest", author: "Ken Kesey" },
    { title: "Catch-22", author: "Joseph Heller" },
    { title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
    { title: "Fahrenheit 451", author: "Ray Bradbury" },
    { title: "On the Road", author: "Jack Kerouac" },
    { title: "The Stranger", author: "Albert Camus" },
    { title: "The Plague", author: "Albert Camus" },
    { title: "The Fall", author: "Albert Camus" },
    { title: "Nausea", author: "Jean-Paul Sartre" },
    { title: "No Exit", author: "Jean-Paul Sartre" },
    { title: "One Hundred Years of Solitude", author: "Gabriel García Márquez" },
    { title: "Love in the Time of Cholera", author: "Gabriel García Márquez" },

    { title: "Invisible Man", author: "Ralph Ellison" },
    { title: "Native Son", author: "Richard Wright" },
    { title: "Black Boy", author: "Richard Wright" },
    { title: "Beloved", author: "Toni Morrison" },
    { title: "Song of Solomon", author: "Toni Morrison" },
    { title: "The Bluest Eye", author: "Toni Morrison" },
    { title: "Their Eyes Were Watching God", author: "Zora Neale Hurston" },
    { title: "The Sound and the Fury", author: "William Faulkner" },
    { title: "As I Lay Dying", author: "William Faulkner" },
    { title: "Light in August", author: "William Faulkner" },
    { title: "Absalom, Absalom!", author: "William Faulkner" },
    { title: "Go Tell It on the Mountain", author: "James Baldwin" },
    { title: "The Fire Next Time", author: "James Baldwin" },
    { title: "Giovanni's Room", author: "James Baldwin" },

    { title: "Leaves of Grass", author: "Walt Whitman" },
    { title: "The Waste Land", author: "T.S. Eliot" },
    { title: "Four Quartets", author: "T.S. Eliot" },
    { title: "The Love Song of J. Alfred Prufrock", author: "T.S. Eliot" },
    { title: "Songs of Innocence and Experience", author: "William Blake" },
    { title: "Paradise Lost", author: "John Milton" },
    { title: "The Rime of the Ancient Mariner", author: "Samuel Taylor Coleridge" },
    { title: "Lyrical Ballads", author: "William Wordsworth and Samuel Taylor Coleridge" },

    { title: "Things Fall Apart", author: "Chinua Achebe" },
    { title: "Arrow of God", author: "Chinua Achebe" },
    { title: "No Longer at Ease", author: "Chinua Achebe" },
    { title: "The Tale of Genji", author: "Murasaki Shikibu" },
    { title: "Norwegian Wood", author: "Haruki Murakami" },
    { title: "Kafka on the Shore", author: "Haruki Murakami" },
    { title: "The Wind-Up Bird Chronicle", author: "Haruki Murakami" },
];

const classicTitlePrefixes = [
    "Analyzing",
    "Understanding",
    "Interpreting",
    "Reading",
    "Exploring",
    "Examining",
    "Studying",
    "Dissecting",
    "Deconstructing",
    "Unpacking",
    "A Critical Analysis of",
    "A Close Reading of",
    "An Examination of",
    "A Study of",
    "An Interpretation of",
    "A Review of",
    "A Commentary on",
    "An Introduction to",
    "A Guide to",
    "Understanding the Themes of",
    "The Symbolism in",
    "The Characters of",
    "The Meaning Behind",
    "The Literary Techniques in",
    "The Historical Context of",
    "The Social Commentary in",
    "The Feminist Reading of",
    "The Marxist Interpretation of",
    "The Psychoanalytic Reading of",
    "The Postcolonial Analysis of",
    "The Cultural Significance of",
    "The Religious Themes in",
    "The Political Messages of",
    "The Philosophical Ideas in",
    "The Moral Questions in",
    "Rereading",
    "Revisiting",
    "Rediscovering",
    "Reinterpreting",
    "New Perspectives on",
    "Fresh Insights into",
    "Modern Approaches to",
    "Contemporary Views of",
    "21st Century Reading of",
    "Postmodern Interpretation of",
    "Feminist Critique of",
    "Decolonizing",
    "Contextualizing",
    "Historicizing",
];

const classicTitleSuffixes = [
    "A Critical Review",
    "An Academic Analysis",
    "A Scholarly Examination",
    "A Literary Study",
    "A Close Reading",
    "An In-Depth Analysis",
    "A Comprehensive Study",
    "A Critical Commentary",
    "An Interpretive Guide",
    "A Reader's Companion",
    "A Study Guide",
    "An Academic Commentary",
    "A Critical Introduction",
    "A Literary Analysis",
    "A Thematic Study",
    "A Character Analysis",
    "A Symbolic Reading",
    "A Historical Analysis",
    "A Cultural Study",
    "A Social Commentary",
    "Through Modern Eyes",
    "In Contemporary Context",
    "From New Perspectives",
    "Revisited and Reexamined",
    "A Fresh Interpretation",
    "New Critical Essays",
    "Modern Scholarly Views",
    "21st Century Perspectives",
    "Academic Insights",
    "Critical Reflections",
    "Scholarly Interpretations",
    "Literary Criticism",
    "Academic Essays",
    "Critical Studies",
    "Research Perspectives",
    "Analytical Essays",
    "Interpretive Studies",
    "Critical Approaches",
    "Academic Perspectives",
    "Scholarly Analysis",
    "Literary Commentary",
    "Critical Insights",
    "Academic Review",
    "Scholarly Commentary",
    "Critical Examination",
    "Literary Perspectives",
    "Academic Interpretation",
    "Critical Theory Applied",
    "Postmodern Reading",
    "Feminist Analysis",
];

export function* generateAllClassicAnalysisTitles(): IterableIterator<string> {
    // Generate combinations of prefix + classic title + suffix + edition + book type
    for (const prefix of classicTitlePrefixes) {
        for (const classic of classicTitles) {
            for (const suffix of classicTitleSuffixes) {
                for (const edition of editions) {
                    for (const bookType of bookTypes) {
                        yield `${getRandomCharacter()} ${prefix} ${classic.title}: ${suffix} ${edition} ${bookType}`;
                    }
                }
            }
        }
    }
}
