// Cooking Book Title Generator
// Generates large amounts of unique cookbook titles through systematic combinations

import { editions, bookTypes, getRandomCharacter } from "../util";

const cookingPrefixes = [
    "How to Cook",
    "The Art of Grilling",
    "Mastering the Art of",
    "The Complete Guide to",
    "The Ultimate Recipe for",
    "Cooking with",
    "The Joy of Cooking",
    "Quick and Easy",
    "Gourmet",
    "Homestyle",
    "Traditional",
    "Modern",
    "Classic",
    "Authentic",
    "Delicious",
    "Perfect",
    "Simple",
    "Amazing",
    "Incredible",
    "Mouthwatering",
    "The Best",
    "Secrets of",
    "The Art of",
    "Mastering",
    "Learning to Cook",
    "Cooking Techniques for",
    "The Science of Cooking",
    "Farm to Table",
    "From Scratch",
    "Healthy",
    "Low-Carb",
    "Keto",
    "Vegan",
    "Vegetarian",
    "Gluten-Free",
    "Paleo",
    "Mediterranean",
    "Asian-Style",
    "Italian",
    "French",
    "Mexican",
    "BBQ",
    "Smoked",
    "Grilled",
    "Roasted",
    "Baked",
    "Fried",
    "Steamed",
    "Braised",
    "Slow-Cooked",
    "Pressure Cooker",
    "Air Fryer",
    "One-Pot",
    "Sheet Pan",
    "Cast Iron",
    "Sous Vide",
    "No-Cook",
    "Raw",
    "Fermented",
    "Pickled",
    "Cured",
    "Holiday",
    "Summer",
    "Winter",
    "Comfort Food",
    "Street Food",
    "Fusion",
    "Molecular Gastronomy",
];

const foods = [
    "Steak",
    "Chicken",
    "Pork",
    "Beef",
    "Lamb",
    "Turkey",
    "Duck",
    "Fish",
    "Salmon",
    "Tuna",
    "Cod",
    "Shrimp",
    "Lobster",
    "Crab",
    "Scallops",
    "Mussels",
    "Oysters",
    "Vegetables",
    "Broccoli",
    "Carrots",
    "Potatoes",
    "Sweet Potatoes",
    "Asparagus",
    "Spinach",
    "Kale",
    "Brussels Sprouts",
    "Cauliflower",
    "Mushrooms",
    "Peppers",
    "Onions",
    "Garlic",
    "Tomatoes",
    "Eggplant",
    "Zucchini",
    "Squash",
    "Pumpkin",
    "Corn",
    "Beans",
    "Lentils",
    "Quinoa",
    "Rice",
    "Pasta",
    "Bread",
    "Pizza",
    "Soup",
    "Salad",
    "Eggs",
    "Cheese",
    "Chocolate",
    "Vanilla",
    "Berries",
    "Apples",
    "Oranges",
    "Lemons",
    "Avocados",
    "Nuts",
    "Seeds",
    "Herbs",
    "Spices",
    "Cookies",
    "Cake",
    "Pie",
    "Muffins",
    "Cupcakes",
    "Ice Cream",
    "Pancakes",
    "Waffles",
    "Tacos",
    "Burgers",
    "Sandwiches",
    "Sushi",
    "Ramen",
    "Curry",
    "Stir-Fry",
    "Casseroles",
    "Risotto",
    "Gnocchi",
    "Dumplings",
    "Spring Rolls",
    "Dim Sum",
    "Barbecue",
    "Wings",
    "Ribs",
    "Brisket",
    "Bacon",
    "Sausage",
    "Ham",
    "Jerky",
    "Smoothies",
    "Cocktails",
    "Coffee",
    "Tea",
];

const cookingSuffixes = [
    "Cookbook",
    "Recipes",
    "Kitchen Secrets",
    "Cooking Guide",
    "Recipe Collection",
    "Culinary Adventures",
    "From My Kitchen",
    "Made Easy",
    "Step by Step",
    "For Beginners",
    "Like a Pro",
    "At Home",
    "Every Day",
    "All Year Round",
    "For the Family",
    "Without the Fuss",
    "In 30 Minutes",
    "One Pot Style",
    "Weekend Cooking",
    "Comfort Food",
    "Gourmet Style",
    "Restaurant Quality",
    "Homemade",
    "Fresh and Simple",
    "Healthy Options",
    "Decadent Delights",
    "Kitchen Magic",
    "Flavor Profiles",
    "Cooking Mastery",
    "Recipe Revolution",
];

export function* generateAllCookingTitles(): IterableIterator<string> {
    // Generate combinations of prefix + food + suffix + edition + book type
    for (const prefix of cookingPrefixes) {
        for (const food of foods) {
            for (const suffix of cookingSuffixes) {
                for (const edition of editions) {
                    for (const bookType of bookTypes) {
                        yield `${getRandomCharacter()} ${prefix} ${food}: ${suffix} ${edition} ${bookType}`;
                    }
                }
            }
        }
    }
}
