import { editions, bookTypes, getRandomCharacter } from "../util";

const miscTitles: string[] = [
    "The Sopranos Sessions",
    "Breaking Bad and Philosophy",
    "The Wire: Truth Be Told",
    "Lost and Philosophy",
    "Friends Forever",
    "The Office: The Untold Story",
    "Seinfeld and Philosophy",
    "Mad Men Carousel",
    "Game of Thrones and Philosophy",
    "The Walking Dead Psychology",
    "Star Wars and Philosophy",
    "The Matrix and Philosophy",
    "Pulp Fiction and Philosophy",
    "The Big Lebowski and Philosophy",
    "Batman and Philosophy",
    "X-Men and Philosophy",
    "Harry Potter and Philosophy",
    "Lord of the Rings and Philosophy",
    "The Simpsons and Philosophy",
    "South Park and Philosophy",
    "Chronicles Volume One",
    "Life",
    "Just Kids",
    "Born to Run",
    "Me",
    "The Beautiful Ones",
    "Open Book",
    "Greenlights",
    "33 Revolutions Per Minute",
    "Love Goes to Buildings on Fire",
    "Meet Me in the Bathroom",
    "Please Kill Me",
    "Our Band Could Be Your Life",
    "Rip It Up and Start Again",
    "The Sound of the City",
    "Mystery Train",
    "Stranded",
    "Psychotic Reactions and Carburetor Dung",
    "Can't Stop Won't Stop",
    "Hip Hop America",
    "Masters of Doom",
    "Console Wars",
    "The Ultimate History of Video Games",
    "Blood, Sweat, and Pixels",
    "Press Reset",
    "Ready Player One",
    "Extra Lives",
    "Reality Is Broken",
    "The Art of Game Design",
    "A Theory of Fun for Game Design",
    "The Boys in the Boat",
    "Seabiscuit",
    "Unbroken",
    "Moneyball",
    "The Blind Side",
    "Friday Night Lights",
    "Season of Dreams",
    "The Jordan Rules",
    "When the Game Was Ours",
    "Open",
    "The Last Season",
    "The Breaks of the Game",
    "Playing for Keeps",
    "The Best Game Ever",
    "Badasses",
    "The Competitive Advantage",
    "Swing",
    "The Boys of Summer",
    "Ball Four",
    "Paper Lion",
    "On the Road",
    "Blue Highways",
    "Travels with Charley",
    "The Great Railway Bazaar",
    "A Walk in the Woods",
    "In a Sunburned Country",
    "Neither Here nor There",
    "Notes from a Small Island",
    "The Lost Continent",
    "Wild",
    "Eat Pray Love",
    "Under the Tuscan Sun",
    "A Year in Provence",
    "Video Night in Kathmandu",
    "The Art of Travel",
    "Roads",
    "Turn Right at Machu Picchu",
    "Walking the Amazon",
    "The Beach",
    "Into Thin Air",
    "Bowling Alone",
    "The Power Broker",
    "The Death and Life of Great American Cities",
    "Fast Food Nation",
    "The Jungle",
    "Nickel and Dimed",
    "Working",
    "The Good War",
    "Hard Times",
    "American Dreams",
    "Coming of Age in Mississippi",
    "Let Us Now Praise Famous Men",
    "The Feminine Mystique",
    "Silent Spring",
    "The Other America",
    "The Lonely Crowd",
    "Middletown",
    "Democracy in America",
    "The American Scene",
    "Main Street",
    "The Seventies",
    "Nixonland",
    "The Outfit",
    "Fear and Loathing in Las Vegas",
    "The Electric Kool-Aid Acid Test",
    "All the President's Men",
    "The Final Days",
    "Helter Skelter",
    "In Cold Blood",
    "The Right Stuff",
    "Woodstock Nation",
    "The Age of Aquarius",
    "Revolution for the Hell of It",
    "Soul on Ice",
    "The Greening of America",
    "The Eighties",
    "Morning in America",
    "The Bonfire of the Vanities",
    "Bright Lights, Big City",
    "Less Than Zero",
    "The Preppy Handbook",
    "Official Preppy Handbook",
    "Miami Vice",
    "Moonwalking with Einstein",
    "The Tipping Point",
    "Barbarians at the Gate",
    "Liar's Poker",
    "Den of Thieves",
    "The Predators' Ball",
    "Greed and Glory on Wall Street",
    "The Nineties",
    "Come As You Are",
    "Generation X",
    "Reality Bites Back",
    "The Tao of Physics",
    "The Beauty Myth",
    "Backlash",
    "Men Are from Mars, Women Are from Venus",
    "The Road Less Traveled",
    "Who Moved My Cheese?",
    "The 7 Habits of Highly Effective People",
    "I'm OK - You're OK",
    "Chicken Soup for the Soul",
    "Don't Sweat the Small Stuff",
    "The Celestine Prophecy",
    "The Immortal Life of Henrietta Lacks",
    "The Devil Wears Prada",
    "Kitchen Confidential",
    "Heat",
    "The Omnivore's Dilemma",
    "In Defense of Food",
    "The Botany of Desire",
    "Salt Sugar Fat",
    "The Flavor Bible",
    "On Writing",
    "Bird by Bird",
    "The Writing Life",
    "Several Short Sentences About Writing",
    "The Elements of Style",
    "On Writing Well",
    "The Sense of Style",
    "Made to Stick",
    "Blink",
    "Outliers",
    "Yes Please",
    "Bossypants",
    "Is Everyone Hanging Out Without Me?",
    "The Year of Magical Thinking",
    "Slouching Towards Bethlehem",
    "Operating Instructions",
    "Traveling Mercies",
    "Running with Scissors",
    "Dry",
    "Me Talk Pretty One Day",
    "Naked",
    "Barrel Fever",
    "When You Are Engulfed in Flames",
    "Calypso",
    "A Moveable Feast",
    "The Paris Wife",
    "Wild Swans",
    "Angela's Ashes",
    "Tis",
    "The Power of Now",
    "A New Earth",
    "The Four Agreements",
    "The Secret",
    "Think and Grow Rich",
    "How to Win Friends and Influence People",
    "Emotional Intelligence",
    "Flow",
    "The Happiness Hypothesis",
    "Stumbling on Happiness",
    "Predictably Irrational",
    "Thinking, Fast and Slow",
    "The Black Swan",
    "Antifragile",
    "The Stranger Beside Me",
    "Fatal Vision",
    "The Devil in the White City",
    "I'll Be Gone in the Dark",
    "The Gift of Fear",
    "Mindhunter",
    "My Friend Dahmer",
    "The Executioner's Song",
    "A Brief History of Time",
    "The Universe in a Nutshell",
    "Cosmos",
    "The Demon-Haunted World",
    "The Selfish Gene",
    "The God Delusion",
    "The Elegant Universe",
    "The Fabric of the Cosmos",
    "The Sea Around Us",
    "Last Child in the Woods",
    "The Nature Principle",
    "Desert Solitaire",
    "The Monkey Wrench Gang",
    "Sand County Almanac",
];

const miscTitlePrefixes = [
    "The Complete Guide to",
    "Everything You Need to Know About",
    "The Ultimate Book of",
    "A Fan's Guide to",
    "Behind the Scenes of",
    "The Making of",
    "The Story Behind",
    "An Insider's Look at",
    "The Cultural Impact of",
    "The Psychology of",
    "The Sociology of",
    "The Philosophy of",
    "Understanding",
    "Exploring",
    "Discovering",
    "Uncovering",
    "Revealing",
    "Demystifying",
    "The Phenomenon of",
    "The Rise and Fall of",
    "The Golden Age of",
    "The Best of",
    "The Worst of",
    "The History of",
    "The Future of",
    "The Secret World of",
    "Life Lessons from",
    "What We Can Learn from",
    "The Genius of",
    "The Art of",
    "The Science of",
    "Pop Culture and",
    "Society and",
    "America and",
    "The World of",
    "Inside",
    "Beyond",
    "Through the Eyes of",
    "A Journey Through",
    "The Evolution of",
    "The Legacy of",
    "Remembering",
    "Celebrating",
    "Honoring",
    "Revisiting",
    "Rediscovering",
    "The Untold Story of",
    "The Real Story of",
    "The True Story of",
    "Myths and Truths About",
    "Facts and Fiction About",
    "The Hidden History of",
    "The Secret Life of",
    "The Cultural Revolution of",
    "Generation",
    "The Age of",
    "The Era of",
    "The Decade of",
    "Living in the",
    "Growing Up in the",
    "Coming of Age in the",
];

const miscTitleSuffixes = [
    "A Pop Culture Analysis",
    "An American Story",
    "A Cultural Phenomenon",
    "A Generation's Journey",
    "A Decade Remembered",
    "An Era Explored",
    "A Social Commentary",
    "A Cultural Study",
    "A Fan's Perspective",
    "An Insider's Account",
    "A Critical Analysis",
    "A Personal Journey",
    "A Nostalgic Look Back",
    "Through the Years",
    "Then and Now",
    "A Retrospective",
    "In Perspective",
    "A Modern Classic",
    "Redefined",
    "Reimagined",
    "Revisited",
    "Remembered",
    "Celebrated",
    "Explored",
    "Examined",
    "Analyzed",
    "Understood",
    "Revealed",
    "Uncovered",
    "Discovered",
    "A Complete Guide",
    "The Definitive Guide",
    "The Ultimate Guide",
    "Everything You Need to Know",
    "A Comprehensive Study",
    "An In-Depth Look",
    "Behind the Scenes",
    "The Inside Story",
    "The Real Story",
    "The Untold Story",
    "A True Story",
    "Based on a True Story",
    "From the Archives",
    "Never Before Told",
    "For the First Time",
    "The Official Story",
    "An Unauthorized Biography",
    "A Personal Account",
    "A Firsthand Experience",
    "Through My Eyes",
    "A Memoir",
    "My Story",
    "Our Story",
    "Their Story",
    "The Story Continues",
    "What Really Happened",
    "The Truth About",
    "Myths and Realities",
    "Facts vs. Fiction",
    "Setting the Record Straight",
];

export function* generateAllMiscAnalysisTitles(): IterableIterator<string> {
    // Generate combinations of prefix + misc title + suffix + edition + book type
    for (const prefix of miscTitlePrefixes) {
        for (const misc of miscTitles) {
            for (const suffix of miscTitleSuffixes) {
                for (const edition of editions) {
                    for (const bookType of bookTypes) {
                        yield `${getRandomCharacter()} ${prefix} ${misc}: ${suffix} ${edition} ${bookType}`;
                    }
                }
            }
        }
    }
}
