const prefixes = ["The", "New", "First", "Great", "Big"];

const suffixes = [
    "Limited",
    "Ltd",
    "LLC",
    "Incorporated",
    "Inc",
    "Corporation",
    "Corp",
    "Company",
    "Co",
    "LLP",
    "LP",
    "Group",
    "Holdings",
    "Enterprises",
    "Associates",
    "Partners",
    "& Associates",
    "& Partners",
    "& Co",
    "& Sons",
    "& Daughters",
    "& Company",
    "International",
    "Global",
    "Worldwide",
    "Universal",
    // Creative/Descriptive suffixes
    "House",
    "Publishing House",
    "Books",
    "Publications",
    "Publishers",
    "Press",
    "Media",
    "Ventures",
    "Solutions",
    "Works",
    "Studio",
    "Workshop",
    "Academy",
    "Institute",
    "Foundation",
    "Society",
    "Union",
    "Alliance",
    "Collective",
    "Network",
    "Guild",
    "Circle",
    "Hub",
    "Labs",
    "Studios",
    "Creative",
    "Digital",
    "Online",
    "Interactive",
    "Modern",
    "Classic",
    "Premium",
    "Elite",
    "Professional",
    "Expert",
    "Master",
    "Pro",
    "Plus",
    "Advanced",
    "Superior",
    "Prime",
    "Select",
    "Exclusive",
    "Signature",
    "Deluxe",
    "Special",
    "Custom",
    "Bespoke",
    "Artisan",
    "Craft",
    "Boutique",
    "Niche",
    "Specialty",
];

const _historyPublishers = [
    "Chronicle Academic Press",
    "Heritage University Publishing",
    "Meridian Historical Studies",
    "Beacon Hill Academic",
    "Westminster Historical Press",
    "Cornerstone University Press",
    "Thornfield Academic Publishing",
    "Riverside Historical Studies",
    "Ashford University Press",
    "Camden Historical Research",
    "Blackwood Academic Press",
    "Whitmore University Publishing",
    "Sterling Historical Studies",
    "Fairfield Academic Press",
    "Grandview University Press",
    "Ancient World Publications",
    "Past & Present Publishing",
    "Historical Horizons Press",
    "Legacy Historical Publishers",
    "Chronicle & Company",
    "Heritage House Books",
    "Antiquarian Press",
    "Classical History Publishing",
    "Eternal History Books",
    "Golden Age Publications",
    "Historical Archives Press",
    "Memory Lane Publishers",
    "Yesteryear Books",
    "Historical Perspectives Press",
    "Old World Publishing House",
    "Medieval Studies Press",
    "Renaissance Era Books",
    "Victorian Age Publishers",
    "Colonial History Press",
    "Ancient Civilizations Books",
    "Empire Studies Publishing",
    "Archaeological Press",
    "Battlefield Books",
    "Maritime History Publishers",
    "Military Heritage Press",
    "Royal History Publications",
    "Diplomatic History Books",
    "Cultural Heritage Press",
    "Social History Publishers",
    "Historian's Library Press",
    "Scholarly Chronicles",
    "Academic Heritage Books",
    "Research Historical Press",
    "Documented History Publishers",
    "Archival Studies Press",
    "Historical Methods Publishing",
    "Primary Sources Press",
    "Manuscript Publications",
    "Historical Evidence Books",
    "Chronological Studies Press",
    "Historical Analysis Publishers",
    "Biographical History Press",
    "Historical Context Books",
    "Timeline Publications",
    "Global History Press",
    "World Chronicles Publishing",
    "International Heritage Books",
    "Continental History Press",
    "Cross-Cultural Studies",
    "Comparative History Publishers",
    "World Civilizations Press",
    "Global Heritage Books",
    "International Chronicles",
    "Multicultural History Press",
    "World History Foundation",
    "Global Perspectives Publishing",
    "International Studies Press",
    "World Heritage Publishers",
    "Cross-Border History Books",
    "Political History Press",
    "Economic History Publishers",
    "Social Movement Books",
    "Religious History Press",
    "Technological Heritage Books",
    "Scientific History Publishers",
    "Medical History Press",
    "Legal Heritage Books",
    "Educational History Publishers",
    "Cultural Studies Press",
    "Anthropological History Books",
    "Geographical History Press",
    "Environmental Heritage Publishers",
    "Agricultural History Books",
    "Industrial Heritage Press",
    "Accessible History Books",
    "Popular Chronicles",
    "History for Everyone Press",
    "General Interest Historical",
    "Mainstream History Publishers",
    "Public History Books",
    "Community Heritage Press",
    "Local History Publishers",
    "Family History Books",
    "Genealogical Heritage Press",
    "Personal History Publishers",
    "Memoir Historical Press",
    "Oral History Books",
    "Living History Publishers",
    "Contemporary History Press",
    "Digital Heritage Books",
    "Online History Publishers",
    "E-Historical Press",
    "Virtual History Books",
    "Interactive History Publishers",
    "Multimedia Heritage Press",
    "Digital Archives Books",
    "Online Chronicles",
    "Cyber History Publishers",
    "Web-Based History Press",
    "Digital Timeline Books",
    "Electronic Heritage Publishers",
    "Online Historical Studies",
    "Digital Memory Press",
    "Virtual Heritage Books",
    "Antique History Publishers",
    "Vintage Historical Press",
    "Classic Chronicles",
    "Retro History Books",
    "Nostalgic Publishers",
    "Timeless Tales Press",
    "Historical Classics",
    "Vintage Heritage Books",
    "Classic Historical Studies",
    "Traditional History Press",
    "Old-School Publishers",
    "Historical Traditions Books",
    "Classic Heritage Press",
    "Vintage Chronicles",
    "Traditional Tales Publishers",
];

const _cookingPublishers = [
    "Culinary Arts Publishing",
    "Kitchen Classics Press",
    "Gourmet Books International",
    "Epicurean Publishing House",
    "Culinary Heritage Books",
    "Kitchen Wisdom Press",
    "Flavor & Taste Publications",
    "Chef's Library Publishing",
    "Culinary Traditions Press",
    "Home Kitchen Publishers",
    "Artisan Food Books",
    "Classic Recipe Press",
    "Culinary Masterpieces",
    "Kitchen Craft Publishing",
    "Seasoned Publishers",
    "Fresh Kitchen Press",
    "Modern Culinary Books",
    "Contemporary Cooking Press",
    "New Age Food Publishers",
    "Trendy Kitchen Books",
    "Urban Cooking Press",
    "Millennial Chef Publishing",
    "Digital Kitchen Books",
    "Social Media Food Press",
    "Viral Recipe Publishers",
    "Instagram Kitchen Books",
    "TikTok Cooking Press",
    "YouTube Chef Publishing",
    "Influencer Food Books",
    "Platform Kitchen Press",
    "Wellness Kitchen Press",
    "Healthy Living Books",
    "Nutritious Recipes Publishing",
    "Clean Eating Press",
    "Whole Foods Publishers",
    "Plant-Based Kitchen Books",
    "Vegan Culinary Press",
    "Vegetarian Recipe House",
    "Raw Food Publishers",
    "Organic Kitchen Books",
    "Farm-to-Table Press",
    "Sustainable Cooking Books",
    "Green Kitchen Publishers",
    "Natural Food Press",
    "Wholesome Recipe Books",
    "Global Kitchen Press",
    "World Flavors Publishing",
    "International Cuisine Books",
    "Ethnic Recipe Publishers",
    "Cultural Kitchen Press",
    "Traditional Foods Books",
    "Regional Cuisine Publishers",
    "Authentic Recipe Press",
    "Heritage Cooking Books",
    "Immigrant Kitchen Press",
    "Fusion Cuisine Publishers",
    "Cross-Cultural Cooking Books",
    "Multi-Ethnic Recipe Press",
    "Diverse Kitchen Publishers",
    "Global Gastronomy Books",
    "Professional Kitchen Press",
    "Master Chef Publishing",
    "Culinary Institute Books",
    "Restaurant Recipe Press",
    "Executive Chef Publishers",
    "Commercial Kitchen Books",
    "Professional Cooking Press",
    "Hospitality Recipe Books",
    "Culinary Academy Press",
    "Industry Kitchen Publishers",
    "Food Service Books",
    "Catering Recipe Press",
    "Banquet Kitchen Publishers",
    "Hotel Cuisine Books",
    "Professional Culinary Press",
    "Family Kitchen Books",
    "Home Chef Publishing",
    "Comfort Food Press",
    "Family Recipe Publishers",
    "Hearth & Home Books",
    "Cozy Kitchen Press",
    "Sunday Dinner Publishers",
    "Grandma's Kitchen Books",
    "Family Tradition Press",
    "Home-Style Cooking Books",
    "Kitchen Table Publishers",
    "Family Feast Press",
    "Comfort Kitchen Books",
    "Homemade Recipe Publishers",
    "Family Cookbook Press",
    "Baking Mastery Press",
    "Pastry Arts Publishers",
    "Dessert Kitchen Books",
    "Bread & Butter Press",
    "Cake Decorating Publishers",
    "BBQ & Grilling Books",
    "Smoker Recipe Press",
    "Outdoor Cooking Publishers",
    "Campfire Kitchen Books",
    "Preservation Press",
    "Canning & Jarring Books",
    "Fermentation Publishers",
    "Cocktail Recipe Press",
    "Beverage Kitchen Books",
    "Wine Pairing Publishers",
    "Fast Kitchen Press",
    "Quick Meal Publishers",
    "30-Minute Recipe Books",
    "Express Cooking Press",
    "Busy Chef Publishers",
    "Rush Hour Kitchen Books",
    "Speed Cooking Press",
    "Instant Recipe Publishers",
    "One-Pot Kitchen Books",
    "Sheet Pan Press",
    "Slow Cooker Publishers",
    "Pressure Cooker Books",
    "Air Fryer Recipe Press",
    "Microwave Kitchen Publishers",
    "No-Cook Recipe Books",
    "Artisan Kitchen Press",
    "Craft Cooking Books",
    "Handmade Recipe Publishers",
    "Small-Batch Kitchen Press",
    "Boutique Food Books",
    "Craft Culinary Publishers",
    "Artisanal Recipe Press",
    "Maker Kitchen Books",
    "DIY Cooking Publishers",
    "Handcrafted Food Press",
    "Local Kitchen Books",
    "Community Recipe Publishers",
    "Neighborhood Kitchen Press",
    "Farmers Market Books",
    "Seasonal Cooking Publishers",
];

const _techPublishers = [
    "Code Craft Publishing",
    "Technical Mastery Press",
    "Digital Architecture Books",
    "Software Engineering Press",
    "Programming Paradigms Publishing",
    "Algorithm & Logic Books",
    "Computer Science Classics",
    "Tech Wisdom Publications",
    "Binary Code Press",
    "System Design Publishers",
    "Pragmatic Programming Press",
    "Code Quality Publications",
    "Software Craftsmanship Books",
    "Technical Excellence Press",
    "JavaScript Mastery Books",
    "Python Power Press",
    "Java Enterprise Publishing",
    "C++ Advanced Books",
    "Rust Programming Press",
    "Go Language Publishers",
    "Swift Development Press",
    "Kotlin Mobile Books",
    "PHP Web Publishers",
    "Frontend Masters Press",
    "Full Stack Publishers",
    "Modern Web Books",
    "Responsive Design Press",
    "Progressive Web Apps Books",
    "CSS Grid Publishers",
    "HTML5 Standards Press",
    "Web Performance Books",
    "Browser API Publishers",
    "JAMstack Press",
    "Serverless Web Books",
    "Microservices Publishers",
    "API Design Press",
    "GraphQL Books",
    "REST Architecture Publishers",
    "Cloud Native Press",
    "DevOps Pipeline Books",
    "Container Technology Publishers",
    "Docker & Kubernetes Press",
    "AWS Cloud Books",
    "Azure Solutions Publishers",
    "Google Cloud Press",
    "Infrastructure as Code Books",
    "CI/CD Publishers",
    "Monitoring & Observability Press",
    "Site Reliability Books",
    "Platform Engineering Publishers",
    "Automation Press",
    "Configuration Management Books",
    "Deployment Strategy Publishers",
    "Data Science Mastery Press",
    "Machine Learning Books",
    "Artificial Intelligence Publishers",
    "Deep Learning Press",
    "Neural Network Books",
    "Big Data Publishers",
    "Analytics & Insights Press",
    "Database Design Books",
    "SQL Mastery Publishers",
    "NoSQL Database Press",
    "Data Pipeline Books",
    "ETL Processing Publishers",
    "Business Intelligence Press",
    "Predictive Analytics Books",
    "Computer Vision Publishers",
    "Cybersecurity Press",
    "Network Security Books",
    "Ethical Hacking Publishers",
    "Penetration Testing Press",
    "Information Security Books",
    "Cryptography Publishers",
    "Network Engineering Press",
    "Protocol Design Books",
    "Firewall & VPN Publishers",
    "Security Architecture Press",
    "Incident Response Books",
    "Digital Forensics Publishers",
    "Privacy Engineering Press",
    "Secure Coding Books",
    "Threat Modeling Publishers",
    "Mobile App Press",
    "iOS Development Books",
    "Android Programming Publishers",
    "React Native Press",
    "Flutter Development Books",
    "Mobile UI Publishers",
    "Cross-Platform Press",
    "Mobile Backend Books",
    "App Store Publishers",
    "Mobile Testing Press",
    "Responsive Mobile Books",
    "Progressive Web App Publishers",
    "Mobile Security Press",
    "Wearable Development Books",
    "IoT Mobile Publishers",
    "Enterprise Architecture Press",
    "Digital Transformation Books",
    "Technology Leadership Publishers",
    "Agile Development Press",
    "Scrum Mastery Books",
    "Product Management Publishers",
    "Technical Strategy Press",
    "Engineering Management Books",
    "Startup Tech Publishers",
    "Scale-Up Engineering Press",
    "Tech Team Books",
    "Remote Development Publishers",
    "Engineering Culture Press",
    "Technical Debt Books",
    "Legacy Systems Publishers",
    "Blockchain Technology Press",
    "Cryptocurrency Books",
    "AR/VR Development Publishers",
    "Quantum Computing Press",
    "Edge Computing Books",
    "5G Technology Publishers",
    "IoT Development Press",
    "Robotics Programming Books",
    "Drone Technology Publishers",
    "3D Printing Press",
    "Autonomous Systems Books",
    "Smart Home Publishers",
    "Wearable Tech Press",
    "Embedded Systems Books",
    "Hardware Programming Publishers",
];

const _miscPublishers = [
    // Academic & University Publishers
    "Academic Press International",
    "University Publishing House",
    "Scholarly Books Ltd",
    "Research Publications Inc",
    "Institute Press",
    "Academy Publishers",
    "Educational Books International",
    "Institutional Press",
    "Metropolitan University Press",
    "Central Academic Publishing",
    "Advanced Studies Press",
    "Graduate Publications",
    "Collegiate Books",
    "Higher Learning Press",
    "Scholarly Works Publishing",
    "Global Publishing Group",
    "International Books Ltd",
    "Worldwide Publications",
    "Universal Press",
    "Continental Publishers",
    "Meridian Publishing House",
    "Atlas Books International",
    "Hemisphere Publishers",
    "Compass Books Ltd",
    "Navigator Publications",
    "Summit Publishing Group",
    "Horizon Books International",
    "Pinnacle Press",
    "Zenith Publications",
    "Apex Publishing House",
    "Modern Publishing Solutions",
    "Contemporary Books Ltd",
    "Progressive Publications",
    "Forward Thinking Press",
    "New Era Publishers",
    "21st Century Books",
    "Millennium Publications",
    "NextGen Publishing House",
    "Future Focus Press",
    "Innovation Books Ltd",
    "Dynamic Publications",
    "Evolving Press",
    "Transformative Publishers",
    "Breakthrough Books",
    "Cutting Edge Publications",
    "Premium Publishing Group",
    "Elite Books Ltd",
    "Prestige Publications",
    "Signature Press",
    "Distinguished Publishers",
    "Excellence Books International",
    "Superior Publications",
    "Quality Press Ltd",
    "Premier Publishing House",
    "First Class Books",
    "Distinction Publications",
    "Refined Press",
    "Luxury Books Ltd",
    "Exclusive Publishers",
    "Select Publications",
    "Heritage Publishing Company",
    "Classic Books Ltd",
    "Traditional Press",
    "Timeless Publications",
    "Established Publishers",
    "Vintage Books International",
    "Legacy Press Ltd",
    "Enduring Publications",
    "Perennial Publishers",
    "Lasting Books",
    "Eternal Press",
    "Foundational Publishers",
    "Cornerstone Books Ltd",
    "Bedrock Publications",
    "Anchor Press",
    "Northern Publishers Ltd",
    "Southern Books International",
    "Eastern Press",
    "Western Publications",
    "Coastal Books Ltd",
    "Mountain View Publishers",
    "Valley Press",
    "Riverside Publications",
    "Lakeside Books",
    "Highland Publishers",
    "Meadow Press Ltd",
    "Woodland Publications",
    "Prairie Books",
    "Desert Publishers",
    "Urban Press Ltd",
    "Enterprise Publications",
    "Corporate Books Ltd",
    "Professional Press",
    "Executive Publishers",
    "Business Solutions Books",
    "Industry Publications",
    "Commercial Press Ltd",
    "Market Leaders Publishers",
    "Success Books International",
    "Achievement Press",
    "Leadership Publications",
    "Strategy Books Ltd",
    "Vision Publishers",
    "Growth Press",
    "Impact Publications",
    "Creative Books Ltd",
    "Artistic Publications",
    "Inspired Press",
    "Imagination Publishers",
    "Vision Books International",
    "Concept Press Ltd",
    "Design Publications",
    "Innovation Books",
    "Creative Solutions Press",
    "Artistic Vision Publishers",
    "Inspiration Books Ltd",
    "Original Publications",
    "Unique Press",
    "Distinctive Publishers",
    "Creative Minds Books",
];

const _classicsPublishers = [
    "Everyman's Library",
    "Oxford Classical Press",
    "Penguin Classics",
    "Modern Library",
    "Cambridge Literary Press",
    "Harvard Classics",
    "Norton Critical Editions",
    "Vintage International",
    "Wordsworth Classics",
    "Dover Publications",
    "Bantam Classics",
    "Signet Classics",
    "Anchor Books",
    "Meridian Classics",
    "New American Library",
    "Barnes & Noble Classics",
    "Collector's Library",
    "Canterbury Classics",
    "Folio Society",
    "Heritage Press",
    "Franklin Library",
    "Easton Press",
    "Library of America",
    "Everyman Paperbacks",
    "World's Classics",
    "Great Books Foundation",
    "Harvard University Press",
    "Yale University Press",
    "Princeton University Press",
    "Columbia University Press",
    "University of Chicago Press",
    "Stanford University Press",
    "Literary Heritage Press",
    "Classic Literature Society",
    "Timeless Tales Publishing",
    "Immortal Works Press",
    "Eternal Classics",
    "Enduring Literature Press",
    "Perennial Wisdom Books",
    "Noble Traditions Publishing",
    "Distinguished Letters Press",
    "Scholarly Classics",
    "Academic Classics Press",
    "Canonical Literature Publishing",
    "Masterpiece Editions",
    "Great Works Publishing",
    "Literary Canon Press",
    "Classical Heritage Books",
    "Renaissance Literature Press",
    "Victorian Classics",
    "Romantic Era Publishing",
    "Enlightenment Press",
    "Ancient Wisdom Books",
    "Medieval Manuscripts Press",
    "Classical Antiquity Publishing",
    "Neoclassical Literature Press",
    "European Classics",
    "British Literature Press",
    "American Heritage Classics",
    "Continental Literature Publishing",
    "World Literature Press",
    "International Classics",
    "Universal Literature Society",
    "Global Literary Heritage",
    "Cross-Cultural Classics",
    "Multilingual Literature Press",
    "Translated Classics",
    "Foreign Literature Society",
    "Comparative Literature Press",
    "Literary Translation House",
    "Cultural Classics Publishing",
    "Metropolitan Classics",
    "Cosmopolitan Literature Press",
    "Bohemian Classics",
    "Avant-Garde Literature Press",
    "Modernist Classics",
    "Experimental Literature Society",
    "Literary Innovation Press",
    "Progressive Classics",
    "Revolutionary Literature Publishing",
    "Romantic Literature Press",
    "Gothic Classics",
    "Sublime Literature Society",
    "Transcendental Press",
    "Naturalist Literature Publishing",
    "Realist Classics",
    "Symbolist Literature Press",
    "Decadent Classics",
    "Fin de Siècle Publishing",
    "Belle Époque Literature Press",
    "Golden Age Classics",
    "Silver Age Literature Society",
    "Classical Mythology Press",
    "Epic Literature Publishing",
    "Tragic Classics",
    "Comic Literature Press",
    "Satirical Classics",
    "Pastoral Literature Society",
    "Bucolic Classics",
    "Heroic Literature Press",
    "Chivalric Classics",
    "Courtly Literature Publishing",
    "Aristocratic Classics",
    "Noble Literature Press",
    "Royal Classics",
    "Imperial Literature Society",
    "Majestic Classics",
    "Regal Literature Press",
    "Crown Classics",
    "Literary Nobility Publishing",
    "Patrician Classics",
    "Genteel Literature Press",
    "Refined Classics",
    "Cultivated Literature Society",
    "Sophisticated Classics",
    "Intellectual Literature Press",
    "Scholarly Wisdom Publishing",
    "Academic Excellence Press",
    "Erudite Classics",
    "Learned Literature Society",
    "Sage Publications",
    "Wisdom Literature Press",
    "Philosophical Classics",
    "Metaphysical Literature Publishing",
    "Transcendent Classics",
    "Spiritual Literature Press",
    "Sacred Classics",
    "Divine Literature Society",
    "Celestial Classics",
    "Heavenly Literature Press",
    "Ethereal Classics",
    "Sublime Literature Publishing",
    "Exalted Classics",
    "Elevated Literature Press",
    "Lofty Classics",
    "Noble Spirit Publishing",
];

// Export cross-joined publisher arrays with prefixes and suffixes
export const historyPublishers = prefixes.flatMap(prefix =>
    _historyPublishers.flatMap(pub => suffixes.map(suffix => prefix + " " + pub + " " + suffix))
);
export const cookingPublishers = prefixes.flatMap(prefix =>
    _cookingPublishers.flatMap(pub => suffixes.map(suffix => prefix + " " + pub + " " + suffix))
);
export const techPublishers = prefixes.flatMap(prefix =>
    _techPublishers.flatMap(pub => suffixes.map(suffix => prefix + " " + pub + " " + suffix))
);
export const miscPublishers = prefixes.flatMap(prefix =>
    _miscPublishers.flatMap(pub => suffixes.map(suffix => prefix + " " + pub + " " + suffix))
);
export const classicsPublishers = prefixes.flatMap(prefix =>
    _classicsPublishers.flatMap(pub => suffixes.map(suffix => prefix + " " + pub + " " + suffix))
);
