// Tech Book Title Generator
// Generates large amounts of unique tech book titles through systematic combinations

import { editions, bookTypes, getRandomCharacter } from "../util";

const techPrefixes = [
    "Learning",
    "Mastering",
    "Exploring",
    "Understanding",
    "Building with",
    "Programming with",
    "Developing with",
    "Advanced",
    "Professional",
    "Expert",
    "Beginning",
    "Intermediate",
    "Complete Guide to",
    "Ultimate Guide to",
    "Comprehensive",
    "Practical",
    "Effective",
    "Modern",
    "Up and Running with",
    "Getting Started with",
    "Hands-On",
    "Real-World",
    "Production-Ready",
    "Enterprise",
    "Scalable",
    "High-Performance",
    "Optimizing",
    "Debugging",
    "Testing",
    "Deploying",
    "Monitoring",
    "Securing",
    "Architecting",
    "Designing",
    "The Art of",
    "The Science of",
    "Best Practices for",
    "Design Patterns in",
    "Algorithms and",
    "Data Structures with",
    "Microservices with",
    "Cloud-Native",
    "Serverless",
    "DevOps with",
    "Agile",
    "Clean Code in",
    "Refactoring",
    "Legacy",
    "Next-Generation",
    "Cutting-Edge",
    "Zero to Hero with",
    "From Beginner to Expert in",
    "Deep Dive into",
    "Inside",
    "Behind the Scenes of",
    "Secrets of",
    "Tips and Tricks for",
    "Hacks and",
    "Unleashing",
    "Unlocking",
    "Demystifying",
    "Simplifying",
    "Accelerated",
    "Rapid",
    "Express",
    "Instant",
    "Quick Start",
    "Fast Track to",
    "Jumpstart",
    "Crash Course in",
    "Bootcamp",
    "Intensive",
    "Essential",
    "Core",
    "Fundamentals of",
];

const techSubjects = [
    // Programming Languages
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "PHP",
    "Ruby",
    "Scala",
    "Clojure",
    "Elixir",
    "Dart",
    "R",
    "MATLAB",
    "Perl",
    "Lua",
    "Haskell",
    "F#",
    "OCaml",
    "Assembly",
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Express.js",
    "Node.js",
    "Deno",
    "HTML5",
    "CSS3",
    "Sass",
    "Less",
    "Bootstrap",
    "Tailwind CSS",
    "jQuery",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "SQLite",
    "Oracle",
    "SQL Server",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Neo4j",
    "InfluxDB",
    "CouchDB",
    "MariaDB",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "CircleCI",
    "Travis CI",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Nagios",
    "Zabbix",
    "Consul",
    "Vault",
    "Nomad",
    "React Native",
    "Flutter",
    "iOS",
    "Android",
    "Xamarin",
    "Ionic",
    "Cordova",
    "PhoneGap",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Jupyter",
    "Apache Spark",
    "Hadoop",
    "Kafka",
    "MLflow",
    "Kubeflow",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Unity",
    "Unreal Engine",
    "Godot",
    "Blender",
    "OpenGL",
    "DirectX",
    "Vulkan",
    "Linux",
    "Windows",
    "macOS",
    "Ubuntu",
    "CentOS",
    "Docker Compose",
    "Vagrant",
    "VirtualBox",
    "VMware",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "TCP/IP",
    "HTTP/HTTPS",
    "DNS",
    "VPN",
    "Firewall",
    "SSL/TLS",
    "OAuth",
    "JWT",
    "LDAP",
    "Active Directory",
    "Kerberos",
    "Wireshark",
    "Nmap",
    "Metasploit",
    "Burp Suite",
    "Spring Boot",
    "Django",
    "Flask",
    "FastAPI",
    "Rails",
    "Laravel",
    "CodeIgniter",
    "Symfony",
    ".NET Core",
    "ASP.NET",
    "Hibernate",
    "JPA",
    "GraphQL",
    "REST APIs",
    "gRPC",
    "Socket.io",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Smart Contracts",
    "Solidity",
    "Web3",
    "NFTs",
    "DeFi",
    "Arduino",
    "Raspberry Pi",
    "IoT",
    "MQTT",
    "LoRaWAN",
    "Zigbee",
    "Bluetooth",
    "WiFi",
];

const techSuffixes = [
    "Signature Series",
    "Complete Reference",
    "Developer's Guide",
    "Programmer's Handbook",
    "Technical Manual",
    "Implementation Guide",
    "Best Practices",
    "Design Patterns",
    "Cookbook",
    "Recipe Book",
    "Solutions Manual",
    "Troubleshooting Guide",
    "Performance Tuning",
    "Optimization Guide",
    "Security Handbook",
    "Admin Guide",
    "User Manual",
    "Quick Reference",
    "Cheat Sheet",
    "Pocket Guide",
    "Field Guide",
    "Survival Guide",
    "Bible",
    "Encyclopedia",
    "Compendium",
    "Masterclass",
    "Workshop",
    "Bootcamp",
    "Tutorial",
    "Step-by-Step Guide",
    "Walkthrough",
    "Deep Dive",
    "Crash Course",
    "Fast Track",
    "Express Learning",
    "Rapid Development",
    "Accelerated Guide",
    "Intensive Course",
    "Comprehensive Course",
    "Complete Course",
    "Full Stack Guide",
    "End-to-End Guide",
    "From Zero to Hero",
    "Beginner to Expert",
    "Fundamentals",
    "Essentials",
    "Core Concepts",
    "Advanced Techniques",
    "Expert Tips",
    "Pro Tips",
    "Insider Secrets",
    "Hidden Features",
    "Power User Guide",
    "Professional Edition",
    "Enterprise Edition",
    "Production Guide",
    "Real-World Examples",
    "Case Studies",
    "Success Stories",
    "War Stories",
    "Lessons Learned",
    "Best of Breed",
    "Industry Standards",
    "Modern Approach",
    "Next-Level Techniques",
    "Cutting-Edge Methods",
    "Revolutionary Practices",
    "Game-Changing Strategies",
    "Proven Methods",
    "Time-Tested Techniques",
    "Battle-Tested Solutions",
    "Production-Ready Code",
    "Scalable Solutions",
    "High-Performance Guide",
    "Cloud-Ready Implementation",
    "Microservices Patterns",
    "Distributed Systems",
    "Machine Learning Edition",
    "AI-Powered Solutions",
    "Data-Driven Approach",
    "Analytics Workbook",
];

export function* generateAllTechTitles(): IterableIterator<string> {
    // Generate combinations of prefix + tech subject + suffix + edition + book type
    for (const prefix of techPrefixes) {
        for (const subject of techSubjects) {
            for (const suffix of techSuffixes) {
                for (const edition of editions) {
                    for (const bookType of bookTypes) {
                        yield `${getRandomCharacter()} ${prefix} ${subject}: ${suffix} ${edition} ${bookType}`;
                    }
                }
            }
        }
    }
}
